### ISSUE TITLE
Error when trying to run eval.py

### ISSUE THREAD

**Issue by BoghosDavtyan** [huliangxiao/GaussianAvatar#27]
Hi,

When I'm trying to evaluate the pre trained "m4c_processed" with the command that provided in the readme:

"python eval.py -s gs_data/data/m4c_processed -m output/m4c_processed --epoch 200"

I get this error:

`
Looking for config file in output/m4c_processed/cfg_args
Config file found: output/m4c_processed/cfg_args
Rendering output/m4c_processed
/home/kfir/anaconda3/envs/gs-avatar/lib/python3.10/site-packages/torchmetrics/utilities/prints.py:62: FutureWarning: Importing `PeakSignalNoiseRatio` from `torchmetrics` was deprecated and will be removed in 2.0. Import `PeakSignalNoiseRatio` from `torchmetrics.image` instead.
  _future_warning(
/home/kfir/anaconda3/envs/gs-avatar/lib/python3.10/site-packages/torchmetrics/utilities/prints.py:62: FutureWarning: Importing `StructuralSimilarityIndexMeasure` from `torchmetrics` was deprecated and will be removed in 2.0. Import `StructuralSimilarityIndexMeasure` from `torchmetrics.image` instead.
  _future_warning(
loading smpl data  /home/kfir/GaussianAvatar/gs_data/data/m4c_processed/train/smpl_parms.pth [14/04 15:20:31]
total pose length 110 [14/04 15:20:31]
Traceback (most recent call last):
  File "/home/kfir/GaussianAvatar/eval.py", line 103, in <module>
    render_sets(model.extract(args), network.extract(args), op.extract(args), args.epoch,)
  File "/home/kfir/GaussianAvatar/eval.py", line 43, in render_sets
    avatarmodel = AvatarModel(model, net, opt, train=False)
  File "/home/kfir/GaussianAvatar/model/avatar_model.py", line 58, in __init__
    self.smpl_model = smplx.SMPL(model_path=self.model_parms.smpl_model_path, gender = self.gender, batch_size = self.batch_size).cuda().eval()
  File "/home/kfir/GaussianAvatar/submodules/smplx/body_models.py", line 143, in __init__
    shapedirs = data_struct.shapedirs
AttributeError: 'NoneType' object has no attribute 'shapedirs'
`

I think I may not installed correctly the SMPL models.

**Comment by wang-zm18** [comment]
The same problem
