### ISSUE TITLE
Errors that occur when using smplx

### ISSUE THREAD

**Issue by hoshizhang** [huliangxiao/GaussianAvatar#47]
Hello, excellent work! As a beginner, I made some mistakes while debugging the code. When I use smpl, both stages can run normally, but when I change self.smpl_type to 'smplx', the following error occurs, I would like to ask you, how should I solve this error? Thank you very much!
![微信截图_20240820191615](https://github.com/user-attachments/assets/0fe16374-773a-471c-ae9f-0f8906b5b5e0)

**Comment by hoshizhang** [comment]
(GaussianAvatar-main) zhantg@zhang-z790-gaming-x-ax:~/桌面/code/GaussianAvatar-main$ CUDA_VISIBLE_DEVICES=0 python train.py -s gs_data_path/m4c_processed -m output/m4c_processed_smplx --train_stage 1
Optimizing output/m4c_processed_smplx
Output folder: output/m4c_processed_smplx [20/08 19:02:27]
loading smpl data  /home/zhantg/桌面/code/GaussianAvatar-main/gs_data_path/m4c_processed/train/smpl_parms.pth [20/08 19:02:27]
total pose length 110 [20/08 19:02:27]
Traceback (most recent call last):
  File "/home/zhantg/桌面/code/GaussianAvatar-main/train.py", line 179, in <module>
    train(lp.extract(args), np.extract(args), op.extract(args), args.save_epochs, args.checkpoint_epochs)
  File "/home/zhantg/桌面/code/GaussianAvatar-main/train.py", line 24, in train
    avatarmodel = AvatarModel(model, net, opt, train=True)
  File "/home/zhantg/桌面/code/GaussianAvatar-main/model/avatar_model.py", line 47, in __init__
    self.smpl_model = smplx.SMPLX(model_path=self.model_parms.smplx_model_path, gender = self.gender, use_pca = False, num_pca_comps = 45, flat_hand_mean = True, batch_size = self.batch_size).cuda().eval()
  File "/home/zhantg/桌面/code/GaussianAvatar-main/submodules/smplx/body_models.py", line 988, in __init__
    super(SMPLX, self).__init__(
  File "/home/zhantg/桌面/code/GaussianAvatar-main/submodules/smplx/body_models.py", line 607, in __init__
    left_hand_components = data_struct.hands_componentsl[:num_pca_comps]
AttributeError: 'Struct' object has no attribute 'hands_componentsl'
