### ISSUE TITLE
train error for smplx

### ISSUE THREAD

**Issue by ZhenyanSun** [huliangxiao/GaussianAvatar#49]
Dear author，
Thanks for your project, I  want to train with smplx with smplx parameters estimated by pymafx, then I met below erros.
***** leye_pose ***** torch.Size([2, 3]) [26/09 11:15:16]
***** reye_pose ***** torch.Size([2, 0]) [26/09 11:15:16]
***** left_hand_pose ***** torch.Size([2, 0]) [26/09 11:15:16]
***** right_hand_pose ***** torch.Size([2, 0]) [26/09 11:15:16]
Traceback (most recent call last):
  File "E:\workspace\GaussianAvatar-main\train.py", line 180, in <module>
    train(lp.extract(args), np.extract(args), op.extract(args), args.save_epochs, args.checkpoint_epochs)
  File "E:\workspace\GaussianAvatar-main\train.py", line 70, in train
    image, points, offset_loss, geo_loss, scale_loss = avatarmodel.train_stage1(batch_data, first_iter)
  File "E:\workspace\GaussianAvatar-main\model\avatar_model.py", line 284, in train_stage1
    live_smpl = self.smpl_model.forward(betas = self.betas,
  File "E:\workspace\GaussianAvatar-main\submodules\smplx\body_models.py", line 1220, in forward
    full_pose = torch.cat([global_orient.reshape(-1, 1, 3),
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 0 for tensor number 4 in the list.
Could you give me some hints for this issues why the left hand pose is empty.

**Comment by huliangxiao** [comment]
Hi, so sorry for the late reply.
I guess there might be an issue with the parameters you estimated from PyMAF.

**Comment by TediousBoredom** [comment]
i met the same error when using the ReFit to get the params. have you solve the problem?

![Image](https://github.com/user-attachments/assets/66375275-13a6-46ef-b4bf-8b8c4a589407)

**Comment by TediousBoredom** [comment]
### i use the code below to process the dynvideo_male data you provide and got this error.
### RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 0 for tensor number 4 in the list.

![Image](https://github.com/user-attachments/assets/3ed4ddb1-cd18-4751-b164-0a72cbb4ce18)

`smpl_model = smplx.SMPLX(model_path='../assets/smpl_files/smplx', gender=gender, use_pca=False, num_pca_comps=45, flat_hand_mean=True, batch_size=1)
        smpl_data = torch.load(os.path.join(data_path, 'smpl_parms.pth'), weights_only=True)
        cano_dir = os.path.join(data_path,)
        
        live_smpl = smpl_model.forward(
            betas=smpl_data['beta'][0][None],
            transl=torch.tensor([[0, 0.35, 0]]),
            global_orient=smplx_cpose_param[:, :3],
            body_pose=smplx_cpose_param[:, 3:66],
            jaw_pose=smplx_cpose_param[:, 66:69],
            leye_pose=smplx_cpose_param[:, 69:72],
            reye_pose=smplx_cpose_param[:, 72:75],
            left_hand_pose=smplx_cpose_param[:, 75:120],
            right_hand_pose=smplx_cpose_param[:, 120:]
        )
        
        ori_vertices = live_smpl.vertices.detach().cpu().numpy().squeeze()
        joint_mat = live_smpl.A
        print(joint_mat.shape)
        torch.save(joint_mat, os.path.join(cano_dir, 'smplx_cano_joint_mat.pth'))
        
        mesh = trimesh.Trimesh(ori_vertices, smpl_model.faces, process=False)
        mesh.export(os.path.join(cano_dir, 'cano_smplx.obj'))`
