### ISSUE TITLE
Rendering novel pose with train_stage 2

### ISSUE THREAD

**Issue by pusacaspica** [huliangxiao/GaussianAvatar#55]
I'm trying to run render_novel_pose.py with train_stage 2. I trained both stages with the m4c_processed dataset, but after rendering 110 images completely blank, just like the one below:

![00000](https://github.com/user-attachments/assets/86418618-730c-4068-9226-c7c61b01e340)

I get the following message error:

```
Traceback (most recent call last):
  File "E:\trabalhos\GaussianAvatar\render_novel_pose.py", line 48, in <module>
    render_sets(model.extract(args), network.extract(args), op.extract(args), args.epoch,)
  File "E:\trabalhos\GaussianAvatar\render_novel_pose.py", line 26, in render_sets
    for idx, batch_data in enumerate(tqdm(novel_pose_loader, desc="Rendering progress")):
  File "C:\Users\pusa\miniconda3\envs\gs-avatar\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\pusa\miniconda3\envs\gs-avatar\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "C:\Users\pusa\miniconda3\envs\gs-avatar\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "C:\Users\pusa\miniconda3\envs\gs-avatar\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "C:\Users\pusa\miniconda3\envs\gs-avatar\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "C:\Users\pusa\miniconda3\envs\gs-avatar\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\pusa\miniconda3\envs\gs-avatar\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\pusa\miniconda3\envs\gs-avatar\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\trabalhos\GaussianAvatar\scene\dataset_mono.py", line 471, in __getitem__
    return self.getitem(index, ignore_list)
  File "C:\Users\pusa\miniconda3\envs\gs-avatar\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\trabalhos\GaussianAvatar\scene\dataset_mono.py", line 479, in getitem
    inp_posmap = np.load(inp_posmap_path)['posmap' + str(self.dataset_parms.inp_posmap_size)]
  File "C:\Users\pusa\miniconda3\envs\gs-avatar\lib\site-packages\numpay\lib\npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\trabalhos\\GaussianAvatar/assets/test_pose/inp_map/inp_posemap_128_00000110.npz'

```

Maybe I'm missing something obvious here, but what could be causing this, and how could I rectify that? Besides the 110 posemaps in m4c_processed's training folder, I cannot find any other posemaps anywhere, nor I can find a way to generate more posemaps (which, speaking - or typing - out loud, doesn't make that much sense).

**Comment by hhxphh** [comment]
me too
I wish the author will provide the test code for the second stage.

**Comment by LucasLOOT** [comment]
i mean i can't render even one images. i meet the error as below:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/sysu/Desktop/animate/GaussianAvatar/assets/test_pose/inp_map/inp_posemap_128_00000000.npz'
`
how can you process the 0-110 images

**Comment by LucasLOOT** [comment]
g.test_folder = os.path.join(args.source_path, "train")
