### ISSUE TITLE
Training Problems

### ISSUE THREAD

**Issue by nagexiaochengzi** [huliangxiao/GaussianAvatar#58]
Has anyone encountered this error? Traceback (most recent call last):
  File "/home/jkx/projects/mjz/GaussianAvatar/train.py", line 179, in <module>
    train(lp.extract(args), np.extract(args), op.extract(args), args.save_epochs, args.checkpoint_epochs)
  File "/home/jkx/projects/mjz/GaussianAvatar/train.py", line 70, in train
    image, points, offset_loss, geo_loss, scale_loss = avatarmodel.train_stage1(batch_data, first_iter)
  File "/home/jkx/projects/mjz/GaussianAvatar/model/avatar_model.py", line 353, in train_stage1
    render_batch(
  File "/home/jkx/projects/mjz/GaussianAvatar/gaussian_renderer/__init__.py", line 40, in render_batch
    rendered_image, _ = rasterizer(
ValueError: too many values to unpack (expected 2)

**Comment by catting123** [comment]
Hello, I encountered the same problem. Have you solved this problem?
